### ISSUE TITLE
Inconsistent formatting of x509 string returned by ClientIdentity.getID()

### ISSUE THREAD

**Issue by kehm** [hyperledger/fabric-chaincode-node#338]
The string returned by ClientIdentity.getID() in Node.js chaincode is formatted differently from the strings returned by Go and Java chaincode. To align with the other two implementations, the order of attributes in each DN should be reversed and forward slash delimeters should be replaced with commas.

An example:
- **Node.js:** x509::/C=US/ST=California/L=San Francisco/OU=COP/CN=peer0.org1.example.com::/C=US/ST=California/L=San Francisco/O=org1.example.com/OU=COP/CN=ca.org1.example.com
- **Go:** x509::CN=peer0.org1.example.com,OU=COP,L=San Francisco,ST=California,C=US::CN=ca.org1.example.com,OU=COP,O=org1.example.com,L=San Francisco,ST=California,C=US
- **Java:** x509::CN=peer0.org1.example.com, OU=COP, L=San Francisco, ST=California, C=US::CN=ca.org1.example.com, OU=COP, O=org1.example.com, L=San Francisco, ST=California, C=US

This caused a bit of confusion for us when experimenting with chaincode written in multiple languages and I would expect that this could be a source of confusion for others as well. I believe that aligning the strings produced by each implementation would make parsing/comparison of the IDs more predictable.

**Comment by mbwhite** [comment]
A good idea; probably only applicable to the main branch (v3.0)
