### ISSUE TITLE
npmjs.com shows latest version @2.2.3

### ISSUE THREAD

**Issue by delaooliveira** [hyperledger/fabric-chaincode-node#344]
Hi folks,

For npmjs.com packages fabric-shim and fabric-contract-api the latest release is still 2.2.3 and not 2.4.2. I don't know if it is within this scope here to upgrade it, but I figured I'd point it out if someone forgot to update the latest version at npmjs.com

**Comment by jt-nti** [comment]
Hi @delaooliveira, thanks for getting in touch. The latest release is still 2.2.x to match the Fabric LTS release strategy...

https://github.com/hyperledger/fabric#releases

Hopefully there will be a new LTS release at some point, and the latest release should then change.

Regards, James
