### ISSUE TITLE
cannot get transaction id and timestamps from getHistoryForKey

### ISSUE THREAD

**Issue by Burnaviour** [hyperledger/fabric-chaincode-node#373]
posting chain code and dependencies res from getHistoryForKey is not returning txid and timestamps

[chaincode and dependencies .zip](https://github.com/hyperledger/fabric-chaincode-node/files/10400713/chaincode.and.dependencies.zip)

**Comment by Tej81r** [comment]
Hi @Burnaviour, 
I am facing the same issue. What was the solution for this?

**Comment by Tej81r** [comment]
I have raised similar query like this.
https://github.com/hyperledger/fabric-chaincode-node/issues/374
Could you please help with this? If this fixed, is this fix available in next patch release?

**Comment by Burnaviour** [comment]
I have fixed this issue

**Comment by Tej81r** [comment]
Could you please point to me to the PR or help me to fix the issue?

**Comment by Burnaviour** [comment]
Follow the instructions provided by Mr White

**Comment by Tej81r** [comment]
Thanks @Burnaviour . I tried to find the instructions. Sorry for asking this if possible could you please any link of instructions by Mr White. I am trying to find solution for this from last 2 days. It would be very helpful for me if you share any link.

**Comment by Tej81r** [comment]
Thanks @Burnaviour .I saw the instructions, but I believe the grpc issue has been resolved in the latest version 2.5.1. Now that I've updated the fabric-shim version to 2.5.1, I'm having trouble with getHistoryForKey (). I believe there is an issue with the most recent version 2.5.1.
