### ISSUE TITLE
iterator of getHistoryForKey() sdk method is not returning the txId and timestamp 

### ISSUE THREAD

**Issue by Tej81r** [hyperledger/fabric-chaincode-node#374]
Hi @mbwhite ,

I work as an Oracle BlockChain Platform developer. Our product "Oracle Blockchain Platform - AppBuilder" is used by end users to create smart contracts based on their business logic. 

Following the grpc issue, we recently upgraded the fabric-shim version to 2.5.1 in Node.js chaincode. The fabric-shim has been updated, and the iterator output of getHistoryForKey(), no longer returns the txId and timestamp. 

The iterator output from getHistoryForKey() previously returned the txId, timestamp, and value; however, in the most recent release, it only returns the value and does not return the **txId** and **timestamp**.

An Example:

getHistoryForKey() iterator result of **fabric-shim 2.2.3**:

 KeyModification {
      txId: '7c8a377c9334075d0770deb844f009fd04200dcb4d485ea449f8a3b8069bba6d',
     value: <Buffer 7b 22 61 73 73 65 74 54 79 70 65 22 3a 22 6f 61 63 63 6f 75 6e 74 22 2c 22 61 63 63 6f 75 6e 74 49 
     64 22 3a 22 6f 61 63 63 6f 75 6e 74 7e 34 32 65 38 ... 136 more bytes>,
     timestamp: Timestamp {
       seconds: Long { low: 1673967527, high: 0, unsigned: false },
      nanos: 346000000
    }
 }

getHistoryForKey() iterator result of **fabric-shim 2.5.1**:

 {
    value: Buffer(729)
 }

Because this is an enterprise organisation, we are only allowed to use the most recent version for licensing purposes, so we cannot use any older versions of the APIs'. So a quick resolution will help us.

**Comment by mbwhite** [comment]
@mergify port main

**Comment by mbwhite** [comment]
Fixed in release 2.5.2
