### ISSUE TITLE
Incorrect Type Definition of ChaincodeResponse

### ISSUE THREAD

**Issue by Jerrylum** [hyperledger/fabric-chaincode-node#413]
`Shim.success` and `Shim.error` functions return `SuccessResponse` and `ErrorResponse`. The return types are defined using JSDoc and both type definitions are also defined using JSDoc in the same file.

However, for the TypeScript definition, `ChaincodeResponse` is used instead. It requires three properties including `status`, `message`, and `payload`. But both users `Shim.success` and `Shim.error` do not return an object with all three properties at the same time. In this case, I believe the type definition of `ChaincodeResponse` is incorrect.

<img width="1379" alt="image" src="https://github.com/hyperledger/fabric-chaincode-node/assets/12783829/65fd13ca-7a5a-4ef9-a734-882c0bf6e17a">

<img width="830" alt="image" src="https://github.com/hyperledger/fabric-chaincode-node/assets/12783829/b2a7dd6a-ab4e-4bc0-b726-c33d85a68aa3">

**Comment by bestbeforetoday** [comment]
I agree. Perhaps the TypeScript types would be better defined like this?

```typescript
interface SuccessResponse {
    status: RESPONSE_CODE.OK;
    message?: string;
    payload: Uint8Array;
}

interface ErrorResponse {
    status: RESPONSE_CODE.ERROR;
    message: string;
    payload?: Uint8Array;
}

type ChaincodeResponse = SuccessResponse | ErrorResponse;

export class Shim {
    static error(msg: Uint8Array): ErrorResponse;
    static success(payload?: Uint8Array): SuccessResponse;
    // ...
}
```

So any fix can properly address your issue, I'm interested to know the impact of this typing mismatch on your use of the API.

**Comment by Jerrylum** [comment]
I think the fix could be the following:

```typescript
interface SuccessResponse { // <- message is unnecessary for SuccessResponse 
    status: ChaincodeStub.RESPONSE_CODE.OK;
    payload: Uint8Array;
}

interface ErrorResponse { // <- payload is unnecessary for ErrorResponse 
    status: ChaincodeStub.RESPONSE_CODE.ERROR;
    message: string;
}

type ChaincodeResponse = SuccessResponse | ErrorResponse;

export class Shim {
    static error(msg: string): ErrorResponse; // <- this should be string instead of Uint8Array
    static success(payload?: Uint8Array): SuccessResponse;
    // ...
}
```

I was writing test cases for my chain code and discovered the issue. Do you think we can make a pull request?

**Comment by bestbeforetoday** [comment]
Definitely you are correct that the error function should take a string parameter: `error(msg: string): ErrorResponse`.

The only slight concern is that the ChaincodeResponse returned from the [ChaincodeInterface methods](https://github.com/hyperledger/fabric-chaincode-node/blob/6126c09be9e48f6d6b6d9e5a0b600c62fc6c3a01/apis/fabric-shim-api/types/index.d.ts#L103-L106) really can be anything that fits the shape:

```typescript
interface ChaincodeResponse {
    status: number;
    message?: string;
    payload? Uint8Array;
}
```

However, this is really an implementation detail only affecting the low-level shim API for implementing chaincode, and the values that actually make sense better fit your type definitions.

Please feel free to open a PR to modify the types as you've described.
